### ISSUE TITLE
Request for Training Data and Model to Reproduce Results

### ISSUE THREAD

**Issue by norgreenk** [MIT-STARLab/deep-learning-ocean-front-detection#1]
Hello, 

I've been using the code and data you provided on this GitHub, but I'm facing difficulties in reproducing the results.

It seems that the training data and model, which were possibly shared on Google Drive in the past, are necessary for accurate reproduction. It seems that that data is no longer publicly available on google drive. Would it be possible for you to share these resources?

I greatly appreciate your work and any assistance you can provide. Thank you in advance for your consideration.

**Comment by Shreeyam** [comment]
Uploaded it to the Google Drive under BOA.zip. Please reach out if you have any more questions!
